#!/bin/bash

#ps -eo fname,rss | awk '{arr[$1]+=$2} END {for (i in arr) {print i,arr[i]"kb"}}' | sort -k2 -nr
ps h -eo fname,pid,rss | awk '{mem[$1]+=$3;pid[$1]=pid[$1]" "$2} END {for (i in mem) {print i,mem[i]"KB",pid[i]}}' | sort -k2 -nr
